modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/pau101/Fairy-Lights/issues"
license="MIT"
[[mods]]
	modId="fairylights"
	version="7.0.0"
	displayName="Fairy Lights"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/fairy-lights"
	authors="pau101"
	description="Fairy Lights introduces decorative string lights, bunting, garland, and more!"
	logoFile="logo.png"
[[dependencies.fairylights]]
	modId="neoforge"
	mandatory=true
	versionRange="[21.1,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.fairylights]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.21.1,1.21.2)"
	ordering="NONE"
	side="BOTH"
